project:
  type: website

website:
  title: "Minhas Operações"
  site-url: "https://ltc0sta.github.io/shofar"
  page-navigation: true

format:
  html:
    theme: minty
    toc: true
    number-sections: false
